import type { Config } from 'tailwindcss';

export default {
	darkMode: ['class'],
	content: ['./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}'],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					'Inter',
					'ui-sans-serif',
					'system-ui',
					'sans-serif',
					'Apple Color Emoji"',
					'Segoe UI Emoji"',
					'Segoe UI Symbol"',
					'Noto Color Emoji"',
				],
				archivo: ['Archivo', 'sans-serif'],
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			colors: {
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					'1': 'hsl(var(--chart-1))',
					'2': 'hsl(var(--chart-2))',
					'3': 'hsl(var(--chart-3))',
					'4': 'hsl(var(--chart-4))',
					'5': 'hsl(var(--chart-5))',
				},
				blue: {
					1: '#091021',
					2: '#0e172c',
					3: '#192642',
					4: '#24314e',
					5: '#2f3e5b',
					6: '#3c4a69',
					7: '#4a5a79',
					8: '#5b6b8b',
					9: '#7384a5',
					10: '#677798',
					11: '#a3b5d8',
					12: '#cfe1ff',
					a1: '#0003f412',
					a2: '#0046ff1d',
					a3: '#3877fd35',
					a4: '#5a8dfd42',
					a5: '#71a0fd50',
					a6: '#84aafd5f',
					a7: '#92b7fd70',
					a8: '#a2c1ff83',
					a9: '#afcaff9f',
					a10: '#a9c5ff91',
					a11: '#bfd4fed6',
					a12: '#cfe1ff',
				},
				'blue-contrast': '#fff',
				'blue-surface': '#0c1d4780',
				'blue-indicator': '#7384a5',
				'blue-track': '#7384a5',
			},
			screens: {
				xxs: '390px',
				xs: '414px',
				boundsXS: '1440px',
				bounds: '1325px',
			},
			borderColor: {
				grayOpacity: 'rgb(56 56 56 / var(--tw-border-opacity))',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
} satisfies Config;
